title = "My Tiny Blog"
baseURL = "https://gitaeron.github.io/"

# Option 1 (recommended): adding the theme as a Hugo module
# theme = "github.com/Lednerb/bilberry-hugo-theme/v3"

# Option 2: cloning/copying the theme files
theme = "bilberry-hugo-theme/v4"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh-cn"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "G-4V01L7ZD0P"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Aeron"
  description = "My Tiny Blog."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 10

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "7G1RL7872T"
  algolia_apiKey    = "345962b42c6bd0887737ec3508c2dcd9"
  algolia_indexName = "gitaeron"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # Enable / Disable comments on the articles via commento
  # commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  # Enable / Disable Giscus comments
  giscus             = false
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "[ENTER REPO HERE]"
  giscusRepositoryId = "[ENTER REPO ID HERE]"
  giscusMapping      = "pathname"
  giscusCategory     = "[ENTER CATEGORY NAME HERE]"
  giscusCategoryId   = "[ENTER CATEGORY ID HERE]"
  giscusTheme        = "light"
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "en"
  giscusCrossOrigin  = "anonymous"

  # Enable / Disable Utterances comments
  utterances            = false
  utterancesJsUrl       = "https://utteranc.es/client.js"
  utterancesRepository  = "[ENTER REPO HERE]"
  utterancesIssueTerm   = "pathname"
  utterancesLabel       = "Comment"
  utterancesTheme       = "github-light"
  utterancesCrossOrigin = "anonymous"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Hello World!"

    # if you want to use libravatar or gravatar for the header image
    avatarEmail = ""

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = "/custom_img/author/pic.png"

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = true

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/article/2023/april/pip-source/"
    
    # Set to true to pin only to the first page, false to all pages
    pinOnlyToFirstPage = true

    # enable highlight.js for syntax highlighting or (if set to false) use
    # the hugo built-in chroma highlighter
    enableHighlightJs = true

    # enable automatic localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 10

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 10

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
    #  { link = "https://twitter.com/TheRealLednerb", icon = "fab fa-twitter", rel = "me" },
    #  { link = "https://github.com/Lednerb", icon = "fab fa-github" },
      { link = "http://scr.im/aeron", icon = "fas fa-envelope"},
      { link = "https://discordapp.com/users/Aeron.Atlantis#2648", icon = "fab fa-discord"},
      { link = "https://github.com/gitaeron/gitaeron.github.io/", icon = "fab fa-github"}
    ]

    # show an archive link in the footer
    showArchive = true

    # archive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006-01"

    # credits line configuration
    copyrightBy = "by Aeron-Atlantis"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2020-2023"
    copyrightUrl = "https://github.com/gitaeron/gitaeron.github.io"
    creditsText = "Most Content Under CC-BY-NC-SA"
    creditsUrl = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# customize your available languages for your multi-lingual site
# or delete one of the [Languages.xx] blocks to use the theme with only one supported language
[Languages]
  [Languages.zh-cn]
    weight = 1
    title = "月下影成双"
    subtitle = "Like the meeting of the seagulls and the waves we meet and come near. The seagulls fly off and the waves roll away we depart."
  [Languages.en]
    weight = 2
    title = "Aeron Atlantis"
    subtitle = "Like the meeting of the seagulls and the waves we meet and come near. The seagulls fly off and the waves roll away we depart."

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

# do NOT change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
